#!/bin/sh
# VNC Startup script
# apt-get install vnc4server tightvncviewer
# apt-get install lxpanel gnome-desktop gnome-panel
# ${HOME}/.vnc/xstartup

export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

/usr/bin/xsetroot -solid grey
/usr/bin/vncconfig -iconic &
/usr/bin/autocutsel &

/usr/bin/gnome-session &
sleep 4 && gnome-panel &
gnome-settings-daemon &
metacity &
gnome-terminal &
nautilus &
lxpanel &
